# Generated by Django 3.2.6 on 2021-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=10, verbose_name='Sigla')),
                ('active', models.BooleanField(verbose_name='Activo')),
                ('floor', models.IntegerField(verbose_name='Piso')),
                ('side', models.CharField(max_length=1, verbose_name='Lado')),
            ],
        ),
    ]
