# Generated by Django 3.2.6 on 2021-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'Dependencia', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='short_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='side',
            field=models.CharField(choices=[('0', 'Frente'), ('1', 'Contrafrente')], max_length=1, verbose_name='Lado'),
        ),
    ]
