# Generated by Django 3.2.6 on 2021-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_auto_20210817_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('activa', models.BooleanField(verbose_name='Activo')),
                ('calle', models.CharField(max_length=70, verbose_name='Calle')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('oficina', models.CharField(max_length=10, verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='active',
            new_name='activa',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='side',
            new_name='lado',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='floor',
            new_name='piso',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='short_name',
            new_name='sigla',
        ),
    ]
