# Generated by Django 3.2.6 on 2021-08-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0003_auto_20210818_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dependencia.sede', verbose_name='Sede'),
            preserve_default=False,
        ),
    ]
