# Generated by Django 3.2.6 on 2021-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0004_dependencia_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='piso',
            field=models.IntegerField(null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='oficina',
            field=models.CharField(blank=True, max_length=10, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='piso',
            field=models.IntegerField(blank=True, verbose_name='Piso'),
        ),
    ]
