# Generated by Django 3.2.6 on 2021-08-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0006_auto_20210818_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='sigla',
        ),
    ]
