# Generated by Django 3.2.6 on 2021-08-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencia', '0002_auto_20210817_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencia.dependencia')),
            ],
        ),
    ]
