# Generated by Django 3.2.6 on 2021-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0009_auto_20210818_0914'),
        ('empleado', '0002_auto_20210818_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='empleado',
            name='dependencia',
            field=models.ManyToManyField(to='dependencia.Dependencia'),
        ),
    ]
